# Generated by Django 3.2.6 on 2022-05-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.ImageField(default='hello', upload_to='blog_photo'),
            preserve_default=False,
        ),
    ]
